package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

import javafx.scene.control.Alert;

import javafx.scene.control.Button;

import javafx.scene.control.PasswordField;

public class MainController implements Initializable {
	@FXML
	private TextField userID;
	@FXML
	private PasswordField password;
	@FXML
	private Label lbUsername;
	@FXML
	private Label lbPassword;
	@FXML
	private Button btnExit;
	@FXML
	private Button btnEnter;

	// Event Listener on Button[#btnExit].onAction
	@FXML
	public void handleButtonExit(ActionEvent event) {
		// TODO Autogenerated
		if(userID.getText().equals(""))
		{
			Alert error = new Alert(Alert.AlertType.ERROR);
			error.setTitle("invalid input");
			error.setHeaderText("The username cannot be empty");
            error.setContentText("Please enter the username");
		}
		else if(password.getText().equals(""))
		{
			Alert error = new Alert(Alert.AlertType.ERROR);
			error.setTitle("invalid input");
			error.setHeaderText("The password cannot be empty");
            error.setContentText("Please enter the password");
		}
		//check if the password match the username
		
	}
	// Event Listener on Button[#btnEnter].onAction
	@FXML
	public void handleButtonEnter(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		
		
	}
}
